name: Test Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: '20'

jobs:
  # =====================================
  # Quick PR Validation
  # =====================================
  validate:
    name: Quick Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for lint issues
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Check build
        run: npm run build

  # =====================================
  # Test Changes
  # =====================================
  test-changes:
    name: Test Changed Packages
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Detect changed packages
        id: changes
        run: |
          echo "Detecting changes in packages..."
          if git diff --name-only origin/main...HEAD | grep -q "packages/core"; then
            echo "core_changed=true" >> $GITHUB_OUTPUT
          fi
          if git diff --name-only origin/main...HEAD | grep -q "packages/web"; then
            echo "web_changed=true" >> $GITHUB_OUTPUT
          fi
          if git diff --name-only origin/main...HEAD | grep -q "packages/mcp"; then
            echo "mcp_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Test Core package
        if: steps.changes.outputs.core_changed == 'true'
        run: npm run test --workspace=@portfolio/core
        continue-on-error: true

      - name: Test Web package
        if: steps.changes.outputs.web_changed == 'true'
        run: npm run test --workspace=@portfolio/web
        continue-on-error: true

      - name: Test MCP package
        if: steps.changes.outputs.mcp_changed == 'true'
        run: npm run test --workspace=@portfolio/mcp
        continue-on-error: true

  # =====================================
  # Preview Deployment
  # =====================================
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    needs: [validate, test-changes]
    
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for Netlify
        run: npm run build:netlify

      - name: Deploy preview to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: 'packages/web/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Preview deploy from PR #${{ github.event.number }}"
          alias: pr-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Test preview deployment
        if: success()
        run: |
          # Wait for deployment to be ready
          sleep 30
          
          # Test the preview deployment
          PREVIEW_URL="https://pr-${{ github.event.number }}--${{ secrets.NETLIFY_SITE_NAME }}.netlify.app"
          npm run test:mcp
        env:
          TEST_MCP_URL: https://pr-${{ github.event.number }}--${{ secrets.NETLIFY_SITE_NAME }}.netlify.app/api/mcp 